### ISSUE TITLE
publish broken - ngx-deploy-npm:deploy for UI and daohaus-connect libs

### ISSUE THREAD

**Issue by brossetti1** [HausDAO/daohaus-monorepo#507]
our master CI is still unable to publish the UI and daohaus-connect-feature libs as new packages to npm. This is coming from the `ngx-deploy-npm: deploy` command in these libs.

https://github.com/HausDAO/daohaus-monorepo/runs/7436964411?check_suite_focus=true#step:10:271

one solution may be to write a `@nrwl/workspace:run-commands` to publish to npm for these libs.

fyi, manually bumping versions has also resulted in intermitent errors - that issue is already cataloged here https://github.com/HausDAO/daohaus-monorepo/issues/322

how to reproduce locally:

```
nx run daohaus-connect-feature:deploy

> nx run daohaus-connect-feature:deploy

📦 Building "daohaus-connect-feature"
📦 Build target "daohaus-connect-feature:build"
Error when trying to deploy daohaus-connect-feature
Error: Cannot read the project path option of the library 'daohaus-connect-feature' in the workspace
    at /Users/brianrossetti/Projects/current/web3/projects/dao-haus-top/daohaus-monorepo-top/daohaus-monorepo/node_modules/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path.js:25:27
    at Generator.next (<anonymous>)
    at /Users/brianrossetti/Projects/current/web3/projects/dao-haus-top/daohaus-monorepo-top/daohaus-monorepo/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/brianrossetti/Projects/current/web3/projects/dao-haus-top/daohaus-monorepo-top/daohaus-monorepo/node_modules/tslib/tslib.js:114:16)
    at withoutOutputPath (/Users/brianrossetti/Projects/current/web3/projects/dao-haus-top/daohaus-monorepo-top/daohaus-monorepo/node_modules/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path.js:23:28)
    at /Users/brianrossetti/Projects/current/web3/projects/dao-haus-top/daohaus-monorepo-top/daohaus-monorepo/node_modules/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path.js:13:20
    at Generator.next (<anonymous>)
    at /Users/brianrossetti/Projects/current/web3/projects/dao-haus-top/daohaus-monorepo-top/daohaus-monorepo/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "daohaus-connect-feature:deploy" failed

   Failed tasks:
```

**Comment by brossetti1** [comment]
fixed by https://github.com/HausDAO/daohaus-monorepo/pull/563/files#diff-43eaee98673a58f1872e4be989f1f5baf15cc03467e7d934f23a6207a410c756L7-R36
